version: '2.1'
services:
  db:
    build:
        dockerfile: ./database/Dockerfile
    image: postgres:9.6
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Brasilio.123
      POSTGRES_USER: postgres
      POSTGRES_DB: DB_Calculadora
    ports:
      - "5432:5432"
  app:
    build:
        dockerfile: ./app/Dockerfile
    ports:
      - "8450:8450"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/DB_Calculadora
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Brasilio.123
    links:
      - db:DB_Calculadora
    depends_on:
      db:
        condition: service_started

  nginx:
    build: ./nginx/Dockerfile
    image: nginx:1.13
    ports:
      - 8000:8454
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static:/opt/services/app/static
      - media:/opt/services/app/media
      
